server:
  port: 8090

spring:
  application:
    name: demo
  cloud:
    sentinel:
      eager: true
      transport:
        port: 8719
        dashboard: localhost:8080
      datasource:
        ds:
          nacos:
            server-addr: localhost:8848
            dataId: nacos-sentinel-demo
            groupId: DEFAULT_GROUP
            ruleType: flow